# Base image
FROM node:20

# Set work dir
WORKDIR /app

# Copy files
COPY package*.json ./
RUN npm install

COPY . .

# Generate Prisma client
RUN npx prisma generate

# Expose port
EXPOSE 3000

# Start app
CMD ["npm", "run", "dev"]
